apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - bin-manager-policies.yaml
  - square-manager-policies.yaml
  - infrastructure-policies.yaml
  - voip-policies.yaml
