apiVersion: v1
kind: ConfigMap
metadata:
  name: voipbin-config
  namespace: bin-manager
data:
  DOMAIN: PLACEHOLDER_DOMAIN
  REDIS_URL: "redis://:PLACEHOLDER_REDIS_PASSWORD@redis.infrastructure.svc.cluster.local:6379/0"
  RABBITMQ_URL: "amqp://PLACEHOLDER_RABBITMQ_USER:PLACEHOLDER_RABBITMQ_PASSWORD@rabbitmq.infrastructure.svc.cluster.local:5672/"
  DB_HOST: "cloudsql-proxy.infrastructure.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: PLACEHOLDER_DB_NAME
  CLOUDSQL_CONNECTION_NAME: PLACEHOLDER_PROJECT_ID:PLACEHOLDER_REGION:PLACEHOLDER_INSTANCE_NAME
  CLICKHOUSE_URL: "http://clickhouse.infrastructure.svc.cluster.local:8123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voipbin-config
  namespace: infrastructure
data:
  DOMAIN: PLACEHOLDER_DOMAIN
  CLOUDSQL_CONNECTION_NAME: PLACEHOLDER_PROJECT_ID:PLACEHOLDER_REGION:PLACEHOLDER_INSTANCE_NAME
