apiVersion: v1
kind: Secret
metadata:
  name: voipbin-secret
  namespace: bin-manager
type: Opaque
stringData:
  JWT_KEY: PLACEHOLDER_JWT_KEY
  DB_USER: PLACEHOLDER_DB_USER
  DB_PASSWORD: PLACEHOLDER_DB_PASSWORD
  REDIS_PASSWORD: PLACEHOLDER_REDIS_PASSWORD
  RABBITMQ_PASSWORD: PLACEHOLDER_RABBITMQ_PASSWORD
  API_SIGNING_KEY: PLACEHOLDER_API_SIGNING_KEY
