apiVersion: v1
kind: Service
metadata:
  name: asterisk-conference-tcp
  namespace: voip
  labels:
    app: asterisk-conference
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: asterisk-conference
  ports:
    - port: 5060
      targetPort: 5060
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: asterisk-conference-udp
  namespace: voip
  labels:
    app: asterisk-conference
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: asterisk-conference
  ports:
    - port: 5060
      targetPort: 5060
      protocol: UDP
