apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voipbin-ingress
  namespace: bin-manager
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.PLACEHOLDER_DOMAIN
        - admin.PLACEHOLDER_DOMAIN
        - talk.PLACEHOLDER_DOMAIN
        - meet.PLACEHOLDER_DOMAIN
      secretName: voipbin-tls
  rules:
    - host: api.PLACEHOLDER_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-manager
                port:
                  number: 443
    - host: admin.PLACEHOLDER_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: square-admin
                port:
                  number: 80
    - host: talk.PLACEHOLDER_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: square-talk
                port:
                  number: 80
    - host: meet.PLACEHOLDER_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: square-meet
                port:
                  number: 80
