apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: infrastructure
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
