apiVersion: apps/v1
kind: Deployment
metadata:
  name: square-admin
  namespace: bin-manager
  labels:
    app: square-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: square-admin
  template:
    metadata:
      labels:
        app: square-admin
    spec:
      containers:
        - name: square-admin
          image: voipbin/square-admin
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: square-admin
  namespace: bin-manager
  labels:
    app: square-admin
spec:
  type: LoadBalancer
  loadBalancerIP: PLACEHOLDER_STATIC_IP_ADDRESS_ADMIN
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: square-admin
