apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: infrastructure
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: PLACEHOLDER_RABBITMQ_USER
  RABBITMQ_DEFAULT_PASS: PLACEHOLDER_RABBITMQ_PASSWORD
