apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infrastructure
  labels:
    app: rabbitmq
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: prometheus
      port: 15692
      targetPort: 15692
  selector:
    app: rabbitmq
