apiVersion: v1
kind: Namespace
metadata:
  name: bin-manager
  labels:
    app.kubernetes.io/part-of: voipbin
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    app.kubernetes.io/part-of: voipbin
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: voip
  labels:
    app.kubernetes.io/part-of: voipbin
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: square-manager
  labels:
    app.kubernetes.io/part-of: voipbin
    pod-security.kubernetes.io/enforce: baseline
