apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: infrastructure
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    databases 16
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
