apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk-registrar
  namespace: voip
  labels:
    app: asterisk-registrar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterisk-registrar
  template:
    metadata:
      labels:
        app: asterisk-registrar
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      terminationGracePeriodSeconds: 7200
      containers:
        - name: asterisk-proxy
          image: voip-asterisk-proxy-image
          imagePullPolicy: Always
          command:
            - "./asterisk-proxy"
          env:
            - name: ARI_ADDRESS
              value: "localhost:8088"
            - name: ARI_ACCOUNT
              value: "asterisk:asterisk"
            - name: ARI_SUBSCRIBE_ALL
              value: "true"
            - name: ARI_APPLICATION
              value: "voipbin"
            - name: AMI_HOST
              value: "127.0.0.1"
            - name: AMI_PORT
              value: "5038"
            - name: AMI_USERNAME
              value: "asterisk"
            - name: AMI_PASSWORD
              value: "asterisk"
            - name: AMI_EVENT_FILTER
              value: ""
            - name: INTERFACE_NAME
              value: "eth0"
            - name: RABBITMQ_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: RABBITMQ_ADDRESS
            - name: RABBITMQ_QUEUE_LISTEN
              value: "asterisk.registrar.request"
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              value: "1"
            - name: PROMETHEUS_ENDPOINT
              value: "/metrics"
            - name: PROMETHEUS_LISTEN_ADDRESS
              value: ":2113"
          resources:
            requests:
              cpu: "5m"
              memory: "5M"
            limits:
              cpu: "50m"
              memory: "50M"
        - name: asterisk
          image: voip-asterisk-registrar-image
          imagePullPolicy: Always
          ports:
            - containerPort: 5060
              name: sip-tcp
              protocol: TCP
            - containerPort: 5060
              name: sip-udp
              protocol: UDP
            - containerPort: 8088
              name: ari
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: voipbin-voip-config
                  key: DOMAIN
            - name: DATABASE_ASTERISK_DATABASE
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_ASTERISK_DATABASE
            - name: DATABASE_ASTERISK_HOST
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_ASTERISK_HOST
            - name: DATABASE_ASTERISK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_ASTERISK_PASSWORD
            - name: DATABASE_ASTERISK_PORT
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_ASTERISK_PORT
            - name: DATABASE_ASTERISK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: voipbin
                  key: DATABASE_ASTERISK_USERNAME
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: "10m"
              memory: "20M"
            limits:
              cpu: "100m"
              memory: "200M"
          lifecycle:
            preStop:
              exec:
                command:
                  - /prestop.sh
