apiVersion: v1
kind: Secret
metadata:
  name: voipbin
  namespace: voip
type: Opaque
stringData:
  RABBITMQ_ADDRESS: PLACEHOLDER_RABBITMQ_ADDRESS
  REDIS_ADDRESS: PLACEHOLDER_REDIS_ADDRESS
  REDIS_PASSWORD: PLACEHOLDER_REDIS_PASSWORD
