apiVersion: v1
kind: Secret
metadata:
  name: voipbin
  namespace: voip
type: Opaque
stringData:
  DATABASE_ASTERISK_DATABASE: "asterisk"
  DATABASE_ASTERISK_HOST: "PLACEHOLDER_CLOUDSQL_PRIVATE_IP"
  DATABASE_ASTERISK_PASSWORD: "dummy-asterisk-password"
  DATABASE_ASTERISK_PORT: "3306"
  DATABASE_ASTERISK_USERNAME: "asterisk"
  KAMAILIO_INTERNAL_LB_ADDRESS: "PLACEHOLDER_KAMAILIO_INTERNAL_LB_ADDRESS"
  KAMAILIO_INTERNAL_LB_NAME: "kamailio-internal-lb"
  RABBITMQ_ADDRESS: "amqp://guest:PLACEHOLDER_RABBITMQ_PASSWORD@rabbitmq.infrastructure.svc.cluster.local:5672"
  REDIS_ADDRESS: "redis.infrastructure.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
