"""Configuration management for VoIPBin installer."""

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import jsonschema
import yaml

from config.defaults import (
    DEFAULT_GKE_MACHINE_TYPE,
    DEFAULT_GKE_NODE_COUNT,
    DEFAULT_KAMAILIO_COUNT,
    DEFAULT_RTPENGINE_COUNT,
    DEFAULT_VM_MACHINE_TYPE,
)
from config.schema import CONFIG_SCHEMA

INSTALLER_VERSION = "1.0.0"


# Keys that must be set (non-empty, non-None) before `build_registry()` can
# safely construct reconcile entries. Missing any of these results in
# `"None"` literals leaking into tf_address / import_id / gcloud argvs
# (GAP-35 shape). See PR-L design doc.
RECONCILE_REQUIRED_KEYS: tuple[str, ...] = ("gcp_project_id", "region")


class InstallerConfig:
    """Manages config.yaml (non-sensitive) for VoIPBin installer."""

    def __init__(self, config_dir: Optional[Path] = None) -> None:
        self._dir = config_dir or Path.cwd()
        self._data: dict[str, Any] = {}

    @property
    def config_path(self) -> Path:
        return self._dir / "config.yaml"

    @property
    def secrets_path(self) -> Path:
        return self._dir / "secrets.yaml"

    def exists(self) -> bool:
        return self.config_path.exists()

    def load(self) -> None:
        """Load config from YAML file."""
        if not self.config_path.exists():
            return
        with open(self.config_path) as f:
            loaded = yaml.safe_load(f)
        if isinstance(loaded, dict):
            self._data = loaded

    def save(self) -> None:
        """Write non-sensitive config to YAML."""
        with open(self.config_path, "w") as f:
            f.write("# VoIPBin Installer Configuration\n")
            f.write(f"# Generated by: voipbin-install init v{INSTALLER_VERSION}\n")
            f.write("# Re-run with: voipbin-install init --reconfigure\n\n")
            yaml.safe_dump(self._data, f, default_flow_style=False, sort_keys=False)

    def get(self, key: str, default: Any = None) -> Any:
        """Get a config value. Environment variables (VOIPBIN_*) take precedence."""
        env_key = f"VOIPBIN_{key.upper()}"
        env_val = os.environ.get(env_key)
        if env_val is not None:
            return env_val
        return self._data.get(key, default)

    def set(self, key: str, value: Any) -> None:
        self._data[key] = value

    def set_many(self, values: dict[str, Any]) -> None:
        self._data.update(values)

    def assert_required(self, keys: tuple[str, ...]) -> None:
        """Hard-fail if any of ``keys`` is missing/None/empty.

        Used by ``terraform_reconcile.build_registry()`` to refuse to
        construct entries when required substitutions (env, project, region)
        are absent — the GAP-35 failure mode.
        """
        # Local import to avoid module-level circular dependency between
        # config and terraform_reconcile (the latter imports the former).
        from scripts.terraform_reconcile import ReconcileRegistryError

        missing = [k for k in keys if not self.get(k)]
        if missing:
            raise ReconcileRegistryError(
                f"Missing required config keys for reconcile: {', '.join(missing)}. "
                f"Hint: run 'voipbin-install init --reconfigure' to set them."
            )


    def validate(self) -> list[str]:
        """Validate config against schema. Returns list of error messages."""
        errors: list[str] = []
        # PR-Z: pre-empt the generic jsonschema "not one of …" message for
        # cert_mode=acme with a clearer hint pointing at PR-AC.
        cm = self._data.get("cert_mode")
        if cm == "acme":
            errors.append(
                "cert_mode=acme is not yet supported. The ACME / Let's "
                "Encrypt path is tracked in PR-AC. For now use "
                "cert_mode=self_signed (default) or cert_mode=manual."
            )
            # Skip schema validation since the enum check would add a noisy
            # duplicate error.
            return errors
        try:
            jsonschema.validate(self._data, CONFIG_SCHEMA)
        except jsonschema.ValidationError as e:
            errors.append(str(e.message))
        except jsonschema.SchemaError as e:
            errors.append(f"Schema error: {e.message}")
        return errors

    def apply_defaults(self) -> None:
        """Set default values for optional fields not already present."""
        defaults = {
            "gke_type": "zonal",
            "tls_strategy": "self-signed",
            "image_tag_strategy": "pinned",
            "dns_mode": "auto",
            "gke_machine_type": DEFAULT_GKE_MACHINE_TYPE,
            "gke_node_count": DEFAULT_GKE_NODE_COUNT,
            "vm_machine_type": DEFAULT_VM_MACHINE_TYPE,
            "kamailio_count": DEFAULT_KAMAILIO_COUNT,
            "rtpengine_count": DEFAULT_RTPENGINE_COUNT,
            "installer_version": INSTALLER_VERSION,
            "init_timestamp": datetime.now(timezone.utc).isoformat(),
            # PR-Z: default cert_mode for Kamailio TLS provisioning.
            "cert_mode": "self_signed",
            # PR-E: cloudsql_private_ip default removed. The field is auto-populated
            # by reconcile_outputs from Terraform output `cloudsql_mysql_private_ip`.
            # If reconcile_outputs hasn't run, the field is absent and the
            # k8s_apply preflight rejects it loudly.
        }
        for k, v in defaults.items():
            if k not in self._data:
                self._data[k] = v

    def to_dict(self) -> dict[str, Any]:
        return dict(self._data)

    def to_terraform_vars(self) -> dict[str, Any]:
        """Return config formatted for Terraform tfvars."""
        return {
            "project_id": self.get("gcp_project_id"),
            "region": self.get("region"),
            "zone": self.get("zone"),
            "gke_type": self.get("gke_type"),
            "gke_machine_type": self.get("gke_machine_type"),
            "gke_node_count": self.get("gke_node_count"),
            "vm_machine_type": self.get("vm_machine_type"),
            "kamailio_count": self.get("kamailio_count"),
            "rtpengine_count": self.get("rtpengine_count"),
            "domain": self.get("domain"),
            "dns_mode": self.get("dns_mode"),
            "tls_strategy": self.get("tls_strategy"),
        }

    def to_ansible_vars(self) -> dict[str, Any]:
        """Return config formatted for Ansible extra vars."""
        return {
            "gcp_project_id": self.get("gcp_project_id"),
            "region": self.get("region"),
            "zone": self.get("zone"),
            "domain": self.get("domain"),
            "tls_strategy": self.get("tls_strategy"),
        }
