apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: heplify-server
    newName: sipcapture/heplify-server
    newTag: "1.30"
  - name: homer-webapp
    newName: pchero/homer-app
    newTag: "0.0.4"
