apiVersion: v1
kind: Service
metadata:
  name: heplify-tcp
  namespace: infrastructure
  labels:
    app: heplify-server
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: heplify-server
  ports:
    - name: hep-server-tcp
      port: 9060
      targetPort: 9060
      protocol: TCP
    - name: hep-server-tls
      port: 9061
      targetPort: 9061
      protocol: TCP
    - name: hep-server-config
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: hep-promport
      port: 9096
      targetPort: 9096
      protocol: TCP
    - name: homer
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: heplify-udp
  namespace: infrastructure
  labels:
    app: heplify-server
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: heplify-server
  ports:
    - name: hep-server-udp
      port: 9060
      targetPort: 9060
      protocol: UDP
